<<<<<<< HEAD
###########################################################################
#
# Generated by : Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Web Edition
#
# Project      : FM_CY6S_KIT
# Revision     : FM_CY6S_KIT
#
# Date         : Sun Mar 15 15:12:40 JST 2026
#
###########################################################################
 
 
=======
###########################################################################
#
# Generated by : Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Web Edition
#
# Project      : FM_CY6S_KIT
# Revision     : FM_CY6S_KIT
#
# Date         : Sun Mar 15 15:12:40 JST 2026
#
###########################################################################
 
 
>>>>>>> 3de807a8631c185695a645c74706bf840139402c
create_clock -name {SysClk} -period 20.0 [get_ports {SysClk}]